version: "3.9"

services:
  ollama:
    build:
      context: ./Ollama  
      dockerfile: Dockerfile 
    container_name: ollama
    networks:
      - app-network
    ports:
      - "11434:11434"  
    volumes: 
      - ollama:/root/.ollama  

  unstructured:
    build:
      context: ./RAG_APP  
      dockerfile: Dockerfile  
    container_name: unstructured
    networks:
      - app-network
    stdin_open: true
    tty: true
    ports:
      - "8501:8501"  
    depends_on:
      - ollama  

networks:
  app-network:

volumes:
  ollama:
