version: "3.9"

services:
  ollama:
    build:
      context: ./Ollama  # Ruta hacia la carpeta de Ollama
      dockerfile: Dockerfile  # Usa el Dockerfile de Ollama
    container_name: ollama
    networks:
      - app-network
    ports:
      - "11434:11434"  # Puerto para Ollama
    volumes:
      - ollama:/root/.ollama  # Volumen para almacenar modelos persistentes

  unstructured:
    build:
      context: ./RAG_APP  # Ruta hacia la carpeta de RAG_APP
      dockerfile: Dockerfile  # Usa el Dockerfile de RAG_APP
    container_name: unstructured
    networks:
      - app-network
    stdin_open: true
    tty: true
    ports:
      - "8501:8501"  # Puerto para Streamlit
    depends_on:
      - ollama  # Asegura que ollama se ejecute antes que unstructured

networks:
  app-network:

volumes:
  ollama:
